#!/usr/bin/env node
/**
 * Reads content/*.yaml and writes the typed src/data/*.generated.ts modules
 * the app imports.
 *
 * Prose lives in YAML rather than in the .ts files directly because a plain
 * YAML scalar takes an apostrophe with no escaping at all: the hand-written
 * versions kept losing a battle between "it's" needing a double-quoted
 * string and a neighbouring string that was already single-quoted, and
 * Prettier silently choosing whichever quote style it preferred on
 * reformat. A block of prose here is just the prose.
 *
 * The .generated.ts files are the ones components import (via the stable
 * src/data/*.ts wrappers, unchanged from before this moved); nothing here
 * else needs to know YAML exists.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { format, resolveConfig } from 'prettier'
import { parse } from 'yaml'

const CONTENT = 'content'
const OUT = 'src/data'

const load = (file) => parse(readFileSync(`${CONTENT}/${file}.yaml`, 'utf8'))

/** A generated file gets the same "do not edit" banner every other one uses. */
const banner = (
  file,
) => `// Generated by scripts/content-build.mjs. Do not edit.
// Source of truth is content/${file}.yaml.
`

/*
 * Run through Prettier on the way out, so a generated file is never the
 * reason `npm run format:check` fails. Editing a paragraph of YAML should
 * not leave the repo needing a formatting pass to go green.
 */
const prettierConfig = await resolveConfig(`${OUT}/about.generated.ts`)

/** A run of prose: plain text, or `{ text, href }` for an inline link. */
const segment = (seg) =>
  typeof seg === 'string'
    ? JSON.stringify(seg)
    : `{ text: ${JSON.stringify(seg.text)}, href: ${JSON.stringify(seg.href)} }`

const paragraphs = (paras) =>
  paras.map((para) => `  [${para.map(segment).join(', ')}],`).join('\n')

const write = async (name, body) => {
  writeFileSync(
    `${OUT}/${name}`,
    await format(body, { ...prettierConfig, parser: 'typescript' }),
  )
  console.log(`  wrote ${OUT}/${name}`)
}

// ─── about ──────────────────────────────────────────────────────────────────
{
  const about = load('about')

  await write(
    'about.generated.ts',
    banner('about') +
      `
/** First professional role, used to derive years in the field. */
export const CAREER_START_YEAR = ${JSON.stringify(about.career_start_year)}

/** A run of prose that may contain inline links. */
export type Segment = string | { text: string; href: string }

export const profile = ${JSON.stringify(
        {
          name: about.profile.name,
          role: about.profile.role,
          tagline: about.profile.tagline,
          cardTagline: about.profile.card_tagline,
          location: about.profile.location,
        },
        null,
        2,
      )} as const

export const aboutParagraphs: Segment[][] = [
${paragraphs(about.paragraphs)}
]
`,
  )
}

// ─── experience ─────────────────────────────────────────────────────────────
{
  const experience = load('experience')

  const role = (r) => ({
    title: r.title,
    company: r.company,
    companyUrl: r.company_url,
    start: r.start,
    ...(r.end ? { end: r.end } : {}),
    summary: r.summary,
    technologies: r.technologies,
    ...(r.clients
      ? {
          clients: r.clients.map((c) => ({
            client: c.client,
            start: c.start,
            ...(c.end ? { end: c.end } : {}),
            summary: c.summary,
            technologies: c.technologies,
          })),
        }
      : {}),
  })

  await write(
    'experience.generated.ts',
    banner('experience') +
      `
/**
 * A single client engagement inside a consulting role. Listed under the role
 * rather than as a role of its own, since the employer never changed.
 */
export interface ClientEngagement {
  /*
   * An industry descriptor, not a company name. Client MSAs typically carry a
   * mutual publicity clause requiring written consent before either party
   * uses the other's name in marketing, and Source Allies anonymises its own
   * case studies this way: three of roughly fifty name the client. Swap in a
   * real name only for a client who has agreed to it in writing.
   */
  client: string
  start: string
  /** Omitted for a current engagement, which renders as "Present". */
  end?: string
  /** Paragraphs, so a long engagement is not one wall of text. */
  summary: string[]
  /** Per engagement, not per role: the stack changes with the client. */
  technologies: string[]
}

export interface ExperienceEntry {
  title: string
  company: string
  companyUrl: string
  start: string
  /** Omitted for the current role, which renders as "Present". */
  end?: string
  summary: string
  technologies: string[]
  /**
   * Consulting roles only. Newest first, like the roles themselves. When
   * present these carry the technology pills, since the role's own list would
   * just be the union of theirs.
   */
  clients?: ClientEngagement[]
}

export const experience: ExperienceEntry[] = ${JSON.stringify(experience.roles.map(role), null, 2)}
`,
  )
}

// ─── outside ────────────────────────────────────────────────────────────────
{
  const outside = load('outside')

  await write(
    'outside.generated.ts',
    banner('outside') +
      `
import type { Segment } from './about.generated'

// Photos come from photos/manifest.json via PhotoCollections.

/**
 * Set large, and read as one block rather than separate paragraphs. The bike
 * tire line is folded in here rather than kept as its own aside: it is the
 * funniest thing on the page, so it belongs at the size people read.
 */
export const outsideLede: string[] = ${JSON.stringify(outside.lede, null, 2)}

/**
 * Body-size paragraphs under the lede, each a run of segments so a sentence
 * can carry a link without being broken up at the call site.
 */
export const outsideBody: Segment[][] = [
${paragraphs(outside.body)}
]
`,
  )
}

// ─── principles ─────────────────────────────────────────────────────────────
{
  const principles = load('principles')

  await write(
    'principles.generated.ts',
    banner('principles') +
      `
export interface Principle {
  title: string
  /** Short framing line, set larger than the body. */
  lede: string
  body: string[]
}

/** Section lede, shared by every design. */
export const valuesLede = ${JSON.stringify(principles.values_lede)}

export const principles: Principle[] = ${JSON.stringify(principles.principles, null, 2)}
`,
  )
}

if (!existsSync(`${OUT}/about.generated.ts`))
  throw new Error('content build did not produce expected output')
